import React from "react";
import { Dialog, DialogContent } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { X, Download, FileText, CheckCircle2, AlertTriangle, TrendingUp, Info } from "lucide-react";
import { Badge } from "@/components/ui/badge";

/**
 * GenericReportViewer
 * 
 * A standardized viewer for reports generated by the system/AI.
 * 
 * Expected `reportData` structure (based on the prompt):
 * {
 *   "titulo": "string",
 *   "resumo_executivo": "string",
 *   "analise_detalhada": { "key": "value" },
 *   "pontos_fortes": ["string"],
 *   "pontos_melhoria": ["string"],
 *   "plano_acao_sugerido": [{ "acao": "string", "prioridade": "string", "prazo_sugerido": "string" }],
 *   "conclusao": "string",
 *   "generated_at": "date string" (optional)
 * }
 */
export default function GenericReportViewer({ open, onClose, reportData, workshop, onDownload, type = "default" }) {
  if (!reportData) return null;

  // Theme colors based on report type
  const getTheme = () => {
    switch (type) {
      case 'financial':
        return {
          header: 'from-emerald-600 to-green-700',
          subHeader: 'from-emerald-50 to-green-50',
          border: 'border-emerald-300',
          text: 'text-emerald-900',
          accent: 'text-emerald-600',
          bgAccent: 'bg-emerald-100'
        };
      case 'hr':
      case 'job-description':
        return {
          header: 'from-purple-600 to-indigo-700',
          subHeader: 'from-purple-50 to-blue-50',
          border: 'border-purple-300',
          text: 'text-purple-900',
          accent: 'text-purple-600',
          bgAccent: 'bg-purple-100'
        };
      case 'operational':
        return {
          header: 'from-blue-600 to-cyan-700',
          subHeader: 'from-blue-50 to-cyan-50',
          border: 'border-blue-300',
          text: 'text-blue-900',
          accent: 'text-blue-600',
          bgAccent: 'bg-blue-100'
        };
      default: // Generic/Strategic
        return {
          header: 'from-slate-700 to-slate-900',
          subHeader: 'from-slate-50 to-gray-50',
          border: 'border-slate-300',
          text: 'text-slate-900',
          accent: 'text-slate-600',
          bgAccent: 'bg-slate-100'
        };
    }
  };

  const theme = getTheme();

  return (
    <Dialog open={open} onOpenChange={onClose}>
      <DialogContent className="max-w-5xl max-h-[95vh] overflow-y-auto p-0 gap-0">
        
        {/* Sticky Header */}
        <div className="sticky top-0 bg-white border-b border-gray-200 px-6 py-4 flex items-center justify-between z-10 shadow-sm">
          <div className="flex items-center gap-3">
            <div className={`p-2 rounded-lg ${theme.bgAccent}`}>
              <FileText className={`w-5 h-5 ${theme.accent}`} />
            </div>
            <div>
              <h2 className="text-lg font-bold text-gray-900 leading-tight">
                {reportData.titulo || "Relatório Gerencial"}
              </h2>
              <p className="text-xs text-gray-500">
                Visualização do Relatório
              </p>
            </div>
          </div>
          <div className="flex gap-2">
            {onDownload && (
              <Button onClick={onDownload} variant="outline" size="sm" className="hidden sm:flex">
                <Download className="w-4 h-4 mr-2" />
                Baixar PDF
              </Button>
            )}
            <Button onClick={onClose} variant="ghost" size="icon">
              <X className="w-5 h-5" />
            </Button>
          </div>
        </div>

        <div className="px-6 py-8 space-y-8 bg-gray-50/50 min-h-screen">
          
          {/* Cover / Title Section */}
          <div className={`bg-gradient-to-r ${theme.header} text-white rounded-xl p-8 shadow-lg`}>
            <div className="flex justify-between items-start">
              <div>
                <Badge className="bg-white/20 hover:bg-white/30 text-white border-none mb-4 backdrop-blur-sm">
                  Relatório Oficial
                </Badge>
                <h1 className="text-3xl md:text-4xl font-bold mb-4 tracking-tight">
                  {reportData.titulo || "Relatório"}
                </h1>
                <div className="space-y-1 text-white/90">
                  <p className="font-medium text-lg">{workshop?.name || 'Oficina'}</p>
                  <p className="text-sm opacity-80">
                    {workshop?.city ? `${workshop.city} • ` : ''}
                    {new Date().toLocaleDateString('pt-BR', { 
                      weekday: 'long', 
                      year: 'numeric', 
                      month: 'long', 
                      day: 'numeric' 
                    })}
                  </p>
                </div>
              </div>
              {/* Optional: Add Logo or Icon here if available */}
            </div>
          </div>

          {/* Executive Summary */}
          {reportData.resumo_executivo && (
            <div className="bg-white border border-gray-200 rounded-xl p-6 shadow-sm">
              <h3 className={`text-lg font-bold ${theme.text} mb-4 flex items-center gap-2`}>
                <Info className="w-5 h-5" />
                Resumo Executivo
              </h3>
              <div className="text-gray-700 leading-relaxed whitespace-pre-line text-justify">
                {reportData.resumo_executivo}
              </div>
            </div>
          )}

          {/* Detailed Analysis */}
          {reportData.analise_detalhada && Object.keys(reportData.analise_detalhada).length > 0 && (
            <div className={`bg-gradient-to-br ${theme.subHeader} border-2 ${theme.border} rounded-xl p-6 shadow-sm`}>
              <h3 className={`text-xl font-bold ${theme.text} mb-6`}>
                Análise Detalhada
              </h3>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {Object.entries(reportData.analise_detalhada).map(([key, value], idx) => (
                  <div key={idx} className="bg-white/60 p-4 rounded-lg border border-gray-200/50">
                    <h4 className="font-semibold text-gray-800 mb-2 capitalize">
                      {key.replace(/_/g, ' ')}
                    </h4>
                    <p className="text-gray-600 text-sm leading-relaxed">
                      {value}
                    </p>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Strengths & Improvements Grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            
            {/* Strengths */}
            {reportData.pontos_fortes?.length > 0 && (
              <div className="bg-white border border-green-200 rounded-xl p-6 shadow-sm relative overflow-hidden">
                <div className="absolute top-0 right-0 w-24 h-24 bg-green-50 rounded-bl-full -mr-4 -mt-4 z-0"></div>
                <h3 className="text-lg font-bold text-green-800 mb-4 flex items-center gap-2 relative z-10">
                  <CheckCircle2 className="w-5 h-5" />
                  Pontos Fortes
                </h3>
                <ul className="space-y-3 relative z-10">
                  {reportData.pontos_fortes.map((item, idx) => (
                    <li key={idx} className="flex items-start gap-3 text-gray-700 bg-green-50/50 p-3 rounded-lg">
                      <span className="text-green-600 font-bold mt-0.5">•</span>
                      <span className="text-sm">{item}</span>
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {/* Improvements */}
            {reportData.pontos_melhoria?.length > 0 && (
              <div className="bg-white border border-amber-200 rounded-xl p-6 shadow-sm relative overflow-hidden">
                <div className="absolute top-0 right-0 w-24 h-24 bg-amber-50 rounded-bl-full -mr-4 -mt-4 z-0"></div>
                <h3 className="text-lg font-bold text-amber-800 mb-4 flex items-center gap-2 relative z-10">
                  <AlertTriangle className="w-5 h-5" />
                  Pontos de Melhoria
                </h3>
                <ul className="space-y-3 relative z-10">
                  {reportData.pontos_melhoria.map((item, idx) => (
                    <li key={idx} className="flex items-start gap-3 text-gray-700 bg-amber-50/50 p-3 rounded-lg">
                      <span className="text-amber-600 font-bold mt-0.5">•</span>
                      <span className="text-sm">{item}</span>
                    </li>
                  ))}
                </ul>
              </div>
            )}
          </div>

          {/* Action Plan */}
          {reportData.plano_acao_sugerido?.length > 0 && (
            <div className="bg-white border border-gray-200 rounded-xl p-6 shadow-sm">
              <h3 className={`text-lg font-bold ${theme.text} mb-6 flex items-center gap-2`}>
                <TrendingUp className="w-5 h-5" />
                Plano de Ação Sugerido
              </h3>
              
              <div className="overflow-hidden border border-gray-200 rounded-lg">
                <table className="w-full text-sm text-left">
                  <thead className={`bg-gray-50 ${theme.text} font-semibold uppercase text-xs`}>
                    <tr>
                      <th className="px-6 py-3 tracking-wider">Ação</th>
                      <th className="px-6 py-3 tracking-wider w-32">Prioridade</th>
                      <th className="px-6 py-3 tracking-wider w-40">Prazo Sugerido</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-gray-200 bg-white">
                    {reportData.plano_acao_sugerido.map((action, idx) => (
                      <tr key={idx} className="hover:bg-gray-50 transition-colors">
                        <td className="px-6 py-4 font-medium text-gray-800">
                          {action.acao}
                        </td>
                        <td className="px-6 py-4">
                          <Badge variant="outline" className={`
                            ${action.prioridade?.toLowerCase().includes('alta') ? 'bg-red-50 text-red-700 border-red-200' : 
                              action.prioridade?.toLowerCase().includes('media') ? 'bg-amber-50 text-amber-700 border-amber-200' : 
                              'bg-blue-50 text-blue-700 border-blue-200'}
                          `}>
                            {action.prioridade}
                          </Badge>
                        </td>
                        <td className="px-6 py-4 text-gray-600">
                          {action.prazo_sugerido}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}

          {/* Conclusion */}
          {reportData.conclusao && (
            <div className={`bg-gradient-to-br ${theme.header} text-white rounded-xl p-8 shadow-md text-center`}>
              <h3 className="text-xl font-bold mb-4">Conclusão</h3>
              <p className="leading-relaxed opacity-95 max-w-4xl mx-auto">
                {reportData.conclusao}
              </p>
            </div>
          )}

          {/* Footer Info */}
          <div className="text-center text-gray-400 text-xs py-4">
            <p>Documento gerado automaticamente pelo sistema Oficinas Master</p>
            <p>{new Date().toLocaleString()}</p>
          </div>

        </div>
      </DialogContent>
    </Dialog>
  );
}