import React, { useState, useMemo } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { base44 } from "@/api/base44Client";
import { Shield, UserPlus, Loader2 } from "lucide-react";
import { toast } from "sonner";
import { differenceInDays } from "date-fns";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import UserFormDialog from "@/components/admin/UserFormDialog";
import CadastroUsuarioDiretoModal from "@/components/admin/CadastroUsuarioDiretoModal";
import UserAuditDialog from "@/components/admin/UserAuditDialog";
import UserDetailsDrawer from "@/components/admin/users/UserDetailsDrawer";
import UserTable from "@/components/admin/users/UserTable";
import UserFilters from "@/components/admin/users/UserFilters";
import UserStatsCards from "@/components/admin/users/UserStatsCards";
import PromoteToAdminDialog from "@/components/admin/PromoteToAdminDialog";
import { PermissionRequestForm } from "@/components/rbac/PermissionRequestForm";
import { usePermissionChangeRequest } from "@/components/rbac/hooks/usePermissionChangeRequest";
import AuditHistoryViewer from "@/components/rbac/audit/AuditHistoryViewer";