export const pagePermissions = {
  // Home
  Home: "public_authenticated",

  // Dashboard
  Dashboard: "admin.audit",
  DashboardOverview: "dashboard.view",

  // Admin / Global
  GestaoTenants: "admin.users",
  GestaoEmpresas: "admin.users",
  GestaoUsuariosEmpresas: "admin.users",
  GestaoRBAC: "admin.profiles",
  GestaoPermissoesExternas: "admin.users",
  GestaoOficina: "workshop.view",
  ConfiguracoesKiwify: "admin.system_config",
  Integracoes: "admin.system_config",
  GerenciarPlanos: "admin.system_config",
  AdminProdutividade: "admin.system_config",
  AdminDesafios: "admin.system_config",
  AdminMensagens: "admin.system_config",
  AdminNotificacoes: "admin.system_config",
  GerenciarToursVideos: "admin.system_config",
  AuditoriaPermissoes: "admin.rbac",
  LogsAuditoriaRBAC: "admin.audit",
  UsuariosAdmin: "admin.users",
  MonitoramentoUsuarios: "admin.audit",
  DiagnosticoPlano: "admin.system_config",
  TesteOpenAI: "diagnostics.ai_access",
  AdminQADashboard: "admin",
  AdminTemplatesBacklog: "admin",
  CadastroUsuarioDireto: "admin",
  TestUsuarios: "admin.system_config",
  CalendarioEventos: "admin.system_config",
  GerenciarProcessos: "admin.system_config",

  // Cultura
  CulturaOrganizacional: "culture.view",
  MissaoVisaoValores: "culture.edit",
  DocumentacaoCompleta: "culture.view",
  Regimento: "culture.edit",
  RituaisAculturamento: "culture.manage_rituals",
  Rituais: "culture.manage_rituals",
  CriarRitualMAP: "culture.manage_rituals",
  CronogramaAculturacao: "culture.manage_rituals",
  GerenciarChecklists: "processes.checklists",
  MapaChecklists: "workshop.view",
  RepositorioDocumentos: "documents.upload",
  DocumentosProcessos: "documents.view",

  // Diagnósticos
  SelecionarDiagnostico: "diagnostics.view",
  DiagnosticoDISC: "diagnostics.create",
  ResultadoDISC: "diagnostics.view",
  HistoricoDISC: "diagnostics.view",
  AutoavaliacaoDISC: "diagnostics.create",
  PublicDISC: null,
  PublicNPS: null,
  PublicFeedback: null,
  DiagnosticoMaturidade: "diagnostics.create",
  ResultadoMaturidade: "diagnostics.view",
  AutoavaliacaoMaturidade: "diagnostics.create",
  HistoricoMaturidade: "diagnostics.view",
  DiagnosticoCarga: "diagnostics.create",
  ResultadoCarga: "diagnostics.view",
  AutoavaliacaoCarga: "diagnostics.create",
  DiagnosticoDesempenho: "diagnostics.create",
  ResultadoDesempenho: "diagnostics.view",
  AutoavaliacaoDesempenho: "diagnostics.create",
  HistoricoDesempenho: "diagnostics.view",
  MatrizDesempenho: "diagnostics.view",
  DiagnosticoEmpresario: "diagnostics.create",
  ResultadoEmpresario: "diagnostics.view",
  AutoavaliacaoEmpresarial: "diagnostics.create",
  DiagnosticoEndividamento: "financeiro.view",
  ResultadoEndividamento: "diagnostics.view",
  AutoavaliacaoEndividamento: "diagnostics.create",
  DiagnosticoGerencial: "diagnostics.create",
  ResultadoGerencial: "diagnostics.view",
  AutoavaliacaoGerencial: "diagnostics.create",
  DiagnosticoOS: "diagnostics.create",
  ResultadoOS: "diagnostics.view",
  AutoavaliacaoOS: "diagnostics.create",
  DiagnosticoProducao: "diagnostics.create",
  ResultadoProducao: "diagnostics.view",
  AutoavaliacaoProducao: "diagnostics.create",
  GraficosProducao: "diagnostics.view",
  DiagnosticoComercial: "diagnostics.create",
  ResultadoComercial: "diagnostics.view",
  AutoavaliacaoComercial: "diagnostics.create",
  DiagnosticoFinanceiro: "diagnostics.create",
  ResultadoFinanceiro: "diagnostics.view",
  AutoavaliacaoFinanceiro: "diagnostics.create",
  DiagnosticoVendas: "diagnostics.create",
  ResultadoVendas: "diagnostics.view",
  AutoavaliacaoVendas: "diagnostics.create",
  DiagnosticoMarketing: "diagnostics.create",
  ResultadoMarketing: "diagnostics.view",
  AutoavaliacaoMarketing: "diagnostics.create",
  DiagnosticoPessoas: "diagnostics.create",
  ResultadoPessoas: "diagnostics.view",
  AutoavaliacaoPessoas: "diagnostics.create",
  DiagnosticoMA3: "diagnostics.create",
  ResultadoMA3: "diagnostics.view",
  AutoavaliacaoMA3: "diagnostics.create",
  CentralAvaliacoes: "diagnostics.view",
  HistoricoDiagnosticos: "diagnostics.view",
  Historico: "diagnostics.view",
  DiagnosticoRiscos: "diagnostics.view",
  DashboardTempoAtencao: "acceleration.manage",

  // Pessoas / Colaboradores
  Colaboradores: "employees.view",
  CadastroColaborador: "employees.create",
  ConvidarColaborador: "employees.create",
  DetalhesColaborador: "employees.view",
  DescricoesCargo: "employees.view",
  DescricaoCargos: "employees.view", // legacy
  CriarDescricaoCargo: "employees.create",
  EditarDescricaoCargo: "employees.edit",
  PortalColaborador: "public_authenticated",
  CDCList: "processes.view",
  CDCForm: "employees.cdc",
  RelatorioCDC: "employees.cdc",
  COEXList: "processes.view",
  COEXForm: "employees.view",
  AnalisesRH: "employees.view",
  MonitoramentoRH: "employees.view",
  Feedbacks: "employees.feedback",
  PesquisaClima: "culture.view",
  ResponderPesquisaClima: "public_authenticated",
  ResultadoClima: "employees.climate",
  Autoavaliacoes: "diagnostics.view",
  Organograma: "workshop.view",
  OrganogramaFuncional: "workshop.view",
  GestaoRoles: "admin.rbac",
  GerenciarRoles: "admin.rbac",
  DocumentacaoRBAC: "admin.rbac",
  CESPECanal: "employees.create",
  CESPEEntrevista: "employees.create",
  CESPEIntegracao: "employees.create",
  CESPEProposta: "employees.create",
  CESPESonho: "employees.create",

  // Treinamentos
  AcademiaTreinamento: "training.view",
  GerenciarTreinamentos: "training.manage",
  MeusTreinamentos: "training.view",
  AssistirCurso: "public_authenticated",
  AssistirAula: "public_authenticated",
  ConfiguracaoAcademia: "training.manage",
  AcompanhamentoTreinamento: "training.evaluate",
  GerenciarAula: "training.manage",
  GerenciarModulo: "training.manage",
  GerenciarModulosCurso: "training.manage",

  // Gamificação
  Gamificacao: "operations.view_qgp",
  RankingBrasil: "public_authenticated",
  Desafios: "public_authenticated",

  // Gestão
  PainelMetas: "goals.view",
  DesdobramentoMeta: "workshop.manage_goals",
  HistoricoMetas: "workshop.manage_goals",
  PainelAcoes: "actions.view",
  PlanoAcao: "operations.manage_tasks",
  Tarefas: "operations.manage_tasks",
  RegistroDiario: "operations.daily_log",
  QGPBoard: "operations.view_qgp",
  TechnicianQGP: "operations.view_qgp",
  DicasOperacao: "operations.view_qgp",
  GestaoDesafios: "operations.manage_tasks",
  IAAnalytics: "diagnostics.ai_access",
  RelatoriosAvancados: "analytics.view",
  RelatoriosInteligencia: "workshop.view",
  IntelligenciaCliente: "workshop.view",
  Clientes: "clients.view",
  CadastroSucesso: null,

  // Aceleração / Consultoria
  ControleAceleracao: "acceleration.manage",
  AcessoAceleracao: "acceleration.view",
  PainelClienteAceleracao: "acceleration.view",
  RelatoriosAceleracao: "acceleration.manage",
  CronogramaImplementacao: "acceleration.view",
  CronogramaGeral: "acceleration.view",
  CronogramaDetalhado: "acceleration.view",
  CronogramaConsultoria: "acceleration.view",
  RegistrarAtendimento: "acceleration.manage",
  AvaliarAtendimento: "acceleration.manage",
  MeuAgendamento: "public_authenticated",
  CentralFollowUp: "acceleration.view",
  CentralProximosPassos: "acceleration.view",
  ProximosPassosConsultoria: "acceleration.view",
  ConsultoriaGlobal: "acceleration.view",
  ListagemClientesSprints: "acceleration.view",
  GestaoContratos: "acceleration.manage",

  // Inteligência
  DesesosCliente: "workshop.view",
  DoresAtivas: "workshop.view",
  DuvidasCliente: "workshop.view",
  EvolucoesCliente: "workshop.view",
  RiscosCliente: "workshop.view",
  GerenciarGruposClientes: "acceleration.manage",

  // Processos / Arquivos
  ManualProcessos: "processes.view",
  MeusProcessos: "processes.view",
  VisualizarProcesso: "processes.view",
  EvidenceUpload: "documents.upload",

  // Financeiro
  DRETCMP2: "financeiro.view",
  DreMockup: "financeiro.view",
  DashboardFinanceiro: "admin.system_config",
  ContasReceber: "financeiro.view",
  ContasPagar: "financeiro.view",
  ConciliacaoBancaria: "financeiro.view",
  RelatoriosAnuais: "financeiro.view",
  GerenciarSubcategorias: "admin.financeiro",
  CorrigirParcelasDuplicadas: "admin.financeiro",
  BackfillSaldosHistoricos: "admin.financeiro",
  ConsolidadoMensal: "financeiro.view",

  // Outros utilitarios
  AuditLogs: "admin.audit",
  ChatGestorOficina: "operations.view_qgp",
  ChatQGPTecnico: "operations.technician_qgp",
  ConfiguracoesNotificacao: "dashboard.view",
  MeuPerfil: "public_authenticated",
  Notificacoes: "dashboard.view",
  Questionario: "diagnostics.create",
  RelatorioUsuario: "admin.users",
  ResponderDISC: "public_authenticated",
  ResponderMaturidade: "public_authenticated",
  Resultado: "diagnostics.view",
  ResultadoAutoavaliacao: "diagnostics.view",
  SolicitarPermissoes: "public_authenticated",

  // Planos
  Planos: "public_authenticated",
  BemVindoPlanos: "public_authenticated",
  MeuPlano: "public_authenticated",
  CadastroPlanos: "admin",

  // Primeiros Acessos
  PrimeiroAcesso: null,
  Cadastro: null,
  CompletarPerfil: "public_authenticated",

  // Páginas públicas (sem permissão necessária)
  ClientRegistration: null,
};

/**
 * Verifica se uma página é pública (não requer autenticação)
 */
export function isPublicPage(pageName) {
  return pagePermissions[pageName] === null;
}

/**
 * Obtém a permissão necessária para acessar uma página
 */
export function getRequiredPermission(pageName) {
  return pagePermissions[pageName];
}